name: i2mv
tag: "r768-ortho-nv6-i2mv-sd21"
exp_root_dir: "outputs"
seed: 42

data_cls: up2you.data.up2you_rgb_data.MultiviewPuzzleDataModule
data:
  data_dir: ["data/2K2K.json", "data/CustomHumans.json", "data/Human4DiT.json", "data/THuman2.1.json", "data/X_Humans.json"]
  validation_data_dir: ["data/4D-DRESS.json"]
  ref_background_color: gray
  target_background_color: gray
  train_num_views: 6
  train_num_refs: 8
  val_num_views: 6
  val_num_refs: 10
  default_prompt: "Multi-view Human, Full Body, High Quality, HDR"

  used_data_type: ["ref_rgbs", "target_rgbs", "target_poses_camera"]
  ref_mask_aug_ratio: 0.0

  train_indices: [0, -1]
  val_indices: [0, 16]
  test_indices: [0, 16]

  target_height: 768
  target_width: 768

  ref_height: 768
  ref_width: 768

  batch_size: 1
  num_workers: 16


system_cls: up2you.systems.i2mv_sd21.MVPuzzleI2MVSDSystem
system:
  check_train_every_n_steps: 100
  cleanup_after_validation_step: true
  cleanup_after_test_step: true
  
  pretrained_model_name_or_path: "Manojb/stable-diffusion-2-1-base"
  pretrained_vae_name_or_path: null
  pretrained_adapter_name_or_path: null
  pretrained_unet_name_or_path: null
  pretrained_feature_aggregator_name_or_path: null

  init_adapter_kwargs:
    # Multi-view adapter
    self_attn_processor: "up2you.models.attention_processor.DecoupledMVRowSelfAttnProcessor2_0"
    # Condition encoder
    cond_in_channels: 3
    # Feature selector
    mode: "topk"
    # For training
    copy_attn_weights: true
    zero_init_module_keys: ["to_out_mv", "to_out_ref"]

  init_image_encoder_kwargs:
    model_name: "dinov2_vitl14"
    image_size: 518
  init_feature_aggregator_kwargs:
    pose_img_size: 512
    pose_img_in_chans: 3
    pose_patch_embed_type: "pose_encoder"
    embed_dim: 1024
    patch_size: 16
    aa_order: ['self', 'self', 'cross', 'cross']
    depth: 1
    weight_norm: "none"
    use_mask: true
    spatial_smooth: true
    smooth_method: "avgpool"
    kernel_size: 3

  # Feature selector
  max_select_ratio: 2.0
  random_select_ratio: 0.0

  val_max_select_ratio: 2.0
  val_random_select_ratio: 0.0

  # Training
  train_cond_encoder: true
  trainable_modules: ["_mv", "_ref"]
  train_feature_aggregator: true
  prompt_drop_prob: 0.1
  image_drop_prob: 0.1
  cond_drop_prob: 0.1
  num_reference_image_range: [4, 8]
  front_reference_prob: 0.2
  # Noise sampler
  shift_noise: true
  shift_noise_mode: interpolated
  shift_noise_scale: 8

  use_weight_map_loss: false

  # Evaluation
  eval_seed: 42
  eval_num_inference_steps: 30
  eval_guidance_scale: 3.0
  eval_height: ${data.target_height}
  eval_width: ${data.target_width}

  # optimizer definition
  # you can set different learning rates separately for each group of parameters, but note that if you do this you should specify EVERY trainable parameters
  optimizer:
    name: AdamW
    args:
      lr: 5e-5
      betas: [0.9, 0.999]
      weight_decay: 0.01
    params:
      cond_encoder:
        lr: 5e-5
      unet:
        lr: 5e-5
      feature_aggregator:
        lr: 5e-5

  scheduler:
    name: SequentialLR
    interval: step
    schedulers:
      - name: LinearLR
        interval: step
        args:
          start_factor: 1e-6
          end_factor: 1.0
          total_iters: 2000
      - name: ConstantLR
        interval: step
        args:
          factor: 1.0
          total_iters: 9999999
    milestones: [2000]

trainer:
  max_epochs: 50
  log_every_n_steps: 10
  num_sanity_val_steps: 1
  val_check_interval: 500
  enable_progress_bar: true
  precision: bf16-mixed
  gradient_clip_val: 1.0
  strategy: ddp # deepspeed_stage_2
  accumulate_grad_batches: 1

checkpoint:
  save_last: true # whether to save at each validation time
  save_top_k: -1
  every_n_epochs: 9999 # do not save at all for debug purpose
